import sqlite3

div_a = [
    "GUJAR SAGAR MAHENDRA MANASI", "KACHA HEENAL JEETENDRA HEENA", "KHATI MAHI ANANDSINGH HANSHI",
    "PARMAR ARYA RAMESH SANGEETA", "PATEL ARMAAN AYUB SHAHISTA", "PAWAR ISHAN PRAKASH NILIMA",
    "PAWAR VEDANT NILESH SUJATA", "PUROHIT MORDHAN MUKESH HEENA", "RAMBHIA HET NILESH JIGNA",
    "SANKLECHA PRINCE YOGESHJI HEMANGI", "SHAH HIMANI PRAKASH VIDYULLATA", "SHAH NAITRI SAURABH SHETAL",
    "SINGH PANKAJ KUMAR SUBHASH TUNTUN", "SOLANKI PRISHA DEVENDRA NEELAM", "VARADKAR HRUGVED SAMIR NEELAM",
    "WAGHMODE SANIKA SAYAJI CHHAYA", "WANI DHRUVA DINESH MADHAVI", "AHER SHLOK BHARAT BEBI",
    "AMBERKAR SAMEERA AJAY RESHMA", "ANSARI LAIBA MOHAMMED SAIF SHIFA", "ANSARI MOHD YOOSHE MOHD AZHAR S",
    "BAGGA NIRAJ GOVINDA MANJULA", "BAGWE SUNEET SATYENDRA SHREYA", "BAROT KHUSHI ASHISH PRIYANKA",
    "BHANUSHALI MANAN MUKESH MAMTA", "BHARADWA HEIT KAUSHIK RIDDHI", "BHATIA SAUMYA MANISH DINA",
    "BHATT NAKUL CHYAVAN VAISHALI", "BHOIR HARSHIT VINOD PRANALI", "BIST SAUMYA DEVENDRA BHAVNA",
    "BORICHA PRIYANSH DIPESH BHAKTI", "CHAKOR SUMIT DINKAR SARITA", "CHANDE AARAV BAKUL BHAVANA",
    "CHAUDHARI YUGAL PRAKASH MEGHA", "CHITRODA JAINAV GIRISH DAKSHA", "DARJI BHAVYA CHETAN KINJAL",
    "DAVE PARTHA KAPIL JULIE", "DESAI DHARMI VIPUL PREETY", "DESAI URVA SAMEER PALLAVI",
    "DESHMUKH ARYAN NITIN MANISHA", "DHURI SHRAVANI MAHENDRA ANUSHKA", "DOSHI MIHIR SWAPNIL URVI",
    "DOSHI MOKSH DINESH SUREKHA", "GAIKWAD SAISH VIJAY SHUBHANGI", "GAJULWAR ONKAR NARAYAN SMITA",
    "GALANDE SATYAM HANMANT MAYA", "GANATRA NEEDHI NAROTTAM MAMTA", "GAWAS HARSHITA ARVIND MINAL",
    "GIRDE SIDDHESH RAJU NITA", "GOLKHAW HUSSAIN MUFFAZAL FATEMA", "GUDHKA DRASHTI SAMEER PRIYA",
    "GUJRATHI MITHIL RAHUL RINA", "GUPTA AASHI VIJENDRA PALLAVI", "GUPTA SUSHIL DILIP ANJALI",
    "HAKIM SAMIYAH FAIYAZ LUBNA", "HALDE YADNYESH HEMANT SAPNA", "HARKHANI KREENA YOGESH MANISHA",
    "INAMDAR MOHD UMAR MUZAMMIL K", "JAIN NISHANT PRASHANT NIDHI", "JAIN VANSH VIKRAM PAYAL",
    "JAIN VIDHI JITESH SIMPAL", "JAISWAL AADITYA RAMESHCHANDRA M", "JANI JENIL PARAS GAYATRI",
    "JOSHI KINJAL RAJESH MITTAL", "KALARIA VASU NIRULBHAI SEJALBEN", "KANANI GARVIT HITESH JAYSHREE",
    "MEHTA HETVI NILESH HANSA"
]

div_b = [
    "KARALE ADITYA UMESH MEGHA", "KESUR KARINA AJAY RACHANA", "KEVIN MARIA KAMARAJ JESIKALA",
    "KHODANI MEET AJAY DAKSHA", "KHOT SAHIL ASHOK KALPANA", "KOLI GEERIJA SAGAR RAJANI",
    "KOSAMBI AYUSHI NILKAMAL JAGRUTI", "MAHARANA SATYAJIT BHAGABAN S", "MANDE AJAY SUBHASH ASHA",
    "MARU SWAYAM NIKHIL NEELAM", "MAVANI YUG MAHESHBHAI PARULBEN", "MEWADA TANISHQ HASMUKH RAKSHA",
    "MODI KRISHNA ROHIT DHRITI", "MORE MAITREYA UMESH PRITI", "MOTA SHIVANSH VINOD HEMANGI",
    "MUNOT ABHINANDAN SANTOSH REKHA", "NAGAR PRATHAM MANISH MANSI", "NAIK SWAYAM TATU SARIKA",
    "NAYAK NIMISH VISHANT REENA", "NIWALKAR HIMANSHI VILAS ALKA", "ODEDARA RAJ HARJI HANSABEN",
    "PARAB DHRU TUSHAR SHUBHANGI", "PARADVA RAVI RAMJIBHAI RANJANBEN", "PATEL ALTAIF ALASHAD ARSHIYA",
    "PATEL JAHNVI VIPUL RITA", "PATEL KRISH BHAVESH SMITA", "PATEL MITTAL RAMESHBHAI SHARDA",
    "PATEL SAAD MOHAMMED NAFISA", "PATKI PEEYUSHA PANKAJ VAIJAYANTI", "PRAJAPATI SACHIN RAMAN GIRJA",
    "RAAZI FARHEEN NASIRUDDIN SABA", "RAMPURAWALA KHADIJA ALIASGAR JUMANA", "REDDY MANI ARUN JAYALAXMI",
    "RUGHANI DRUMIL SACHIN DEEPALI", "SAINDANE VINAYAK PRAKASH SHUBHANGI", "SAINI EKTA MANOJ NEELAM",
    "SATOSKAR MAHI SACHIN SUNETRA", "SEDANI HARDIK PRADIP NEHA", "SHAH DHRUV HEMENDRA MALLIKA",
    "SHAH KAVYA DINESH DEEPALI", "SHAH LAVISH PANKAJ NEETA", "SHAH MANAS VIJAY JYOTI",
    "SHAH NEMIL KISHOR BEENA", "SHAH SIDDH UNMESH SHALAKA", "SHAH ZEAL KAMAL DUMPY",
    "SHAIKH SANIYA AMIRUDDIN KANIZ FATIMA", "SHARMA MAITRI KAUSHAL VIJAYALAXMI", "SHEDGE SHLOK PURUSHOTTAM VIDYA",
    "SHIVDAVKAR AMEYA RADHAKRISHNA SARITA", "SIDDIQUI MOHAMMED MUDASSIR MOHD ARIF T", "SOLANKI DHEERAJ SANJAYSINH LEENA",
    "SOLANKI KAUSHIK DINESH NIRMALA", "SONAWANE DWITIYASH NITIN ASHA", "SURANA RUSHABH ANAND REKHA",
    "SUTAR DIVESH DATTATRAYA LATA", "TOMAR AYUSH SURPAL SARITA", "UPALANCHI VIRAJKUMAR SAGAR AARTI",
    "VAJA VIRAJ SUNIL SONA", "VAKHARIA ACHAL DARSHAN ALPA", "VIDHANI ALI HASAN ZILLANI ASTANA",
    "VISHWAKARMA SHUBHAM DILIP NAGINA", "VITMAL RAJ SANDEEP SAKSHI", "WAKORE SHRISHAILESH ARJUN RUPALI",
    "YADAV UTKARSH AMARNATH URMILA"
]

conn = sqlite3.connect('attendance.db')
c = conn.cursor()

count = 0
for i, name in enumerate(div_a):
    student_id = f"A{i+1:02d}"  # A01, A02, etc.
    try:
        c.execute("INSERT INTO students (student_id, name) VALUES (?, ?)", (student_id, name))
        count += 1
    except Exception as e:
        print("Error inserting div_a:", e)

for i, name in enumerate(div_b):
    student_id = f"B{i+1:02d}"  # B01, B02, etc.
    try:
        c.execute("INSERT INTO students (student_id, name) VALUES (?, ?)", (student_id, name))
        count += 1
    except Exception as e:
        print("Error inserting div_b:", e)

conn.commit()
conn.close()
print(f"Added {count} students total!")
